### ISSUE TITLE
depends on deprecated library sodiumoxide

### ISSUE THREAD

**Issue by jonassmedegaard** [etesync/etebase-rs#24]
The sodiumoxide project is now deprecated: https://github.com/sodiumoxide/sodiumoxide/commit/5bb1dfd

**Comment by tasn** [comment]
I think it's not deprecated in terms of DO NOT USE, but rather: it's now feature complete, no?

**Comment by jonassmedegaard** [comment]
Right, that is my understanding as well.

I am no crypto expert, but seem to read between the lines, however, that what the author describes as having "vastly changed" includes maturity of implementations in native Rust, which I would expect to have both size, speed, and stability improvements.

Seems the [Dalek](https://dalek.rs/) libraries (and crates based on those) are the most popular in the Rust community nowadays.

**Comment by tasn** [comment]
The problem is that we can't only care about quality, but we also need to care about compatibility with the algorithms we use (libsodium ones).

Dalek looks great though! I wonder if there's a sodium compatibility layer!

**Comment by jonassmedegaard** [comment]
Perhaps this: https://crates.io/crates/crypto_box

**Comment by tasn** [comment]
Main questions are:
1. is it worth it?
2. Compatibility.

**Comment by Xiretza** [comment]
sodiumoxide is now completely archived and will thus no longer receive security fixes; it should be replaced.

**Comment by tasn** [comment]
:|

OK, I'll try to find some time to take a look, thanks!

**Comment by barathrm** [comment]
I'm looking into finally upstreaming libetebase into openSUSE, and just discovered this one again during the automated cargo audit that's run. 

Friendly bump :hugs:

**Comment by tasn** [comment]
There's nothing wrong with sodiumoxide I believe, it's just "no longer developed". I don't know what it actually means in terms of security, but given that it's just a thin wrapper around libsodium, I'm not *that* concerned. It's going to be quite a bit of work changing to a new implementation, which I don't have time for unfortunately. Especially given the questionable benefits.

**Comment by mainrs** [comment]
> sodiumoxide is now completely archived and will thus no longer receive security fixes; it should be replaced.

This does not seem to be the case: https://github.com/sodiumoxide/sodiumoxide/blob/3057acb1a030ad86ed8892a223d64036ab5e8523/README.md?plain=1#L3-L5

**Comment by Xiretza** [comment]
That message is from before the repo was archived.

**Comment by tjanez** [comment]
I just hit this issue when [talking to Fedora Rust SIG about packaging etebase-rs for Fedora](https://lists.fedoraproject.org/archives/list/rust@lists.fedoraproject.org/thread/KPSEC6OONZDNSVIPXB7P4HTKGN6FXDGJ/).

Fabio Valentini warned that (among all etebase-rs' depencencies):
> The only problematic one I see here is sodiumoxide. This project has been
abandoned and probably really shouldn't be used any longer ... all others
are already packaged for Fedora as far as I can tell.

I think this makes it a blocker for packaging it in its current state.

When I asked Fabio Valentini regarding possible alternatives, he [replied](https://lists.fedoraproject.org/archives/list/rust@lists.fedoraproject.org/message/P6PKWBS7FD7EA3G74P5F4PWXZYX6TAUX/):
> It depends on which functionality from libsodium they need.
They already depend on OpenSSL, I would just use that if possible.

> If OpenSSL doesn't provide everything they need, the RustCrypto
project provides implementations for a lot of things:
https://github.com/RustCrypto

**Comment by tasn** [comment]
The challenge is that the change to either is a complete rewrite of the underlying crypto (and making sure that everything is backwards compatible). It's not a simple change unfortunately. :(

**Comment by Skycoder42** [comment]
Another option could be to depend on just libsodium (C library) and create rust bindings for only the APIs needed as part of this project. This still would be quite some work,  but would not need any rewrites of application code and ensure compatibility

**Comment by tjanez** [comment]
> Another option could be to depend on just libsodium (C library) and create rust bindings for only the APIs needed as part of this project. This still would be quite some work, but would not need any rewrites of application code and ensure compatibility

Could this be a viable path forward?

It would be really great if we could provide etebase-rs and Evolution EteSync plugin in Fedora's upstream repos. And as far as I understand, the sodiumoxide dependency is the only blocker to this.

The user experience with the 3rd party COPR repo has been less than ideal (see: https://gitlab.gnome.org/GNOME/evolution-etesync/-/issues/20), and it would be much better if users could just install it directly from Fedora's repos.

**Comment by tjanez** [comment]
Hey!

Is there any update on the situation?

Meanwhile, [Fedora 45 will upgrade OpenSSL to version 4.0](https://fedoraproject.org/wiki/Changes/OpenSSL40) which makes [libetebase builds fail in Copr](https://gitlab.gnome.org/GNOME/evolution-etesync/-/work_items/22#note_2807203) with:
```
  thread 'main' (336) panicked at /builddir/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-sys-0.9.108/build/main.rs:492:5:


  This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3), or LibreSSL 2.5
  through 4.1.x, but a different version of OpenSSL was found. The build is now aborting
  due to this version mismatch.
```
Full build logs here: https://download.copr.fedorainfracloud.org/results/daftaupe/etesync-rs/fedora-rawhide-aarch64/10699107-libetebase/builder-live.log.gz

**Comment by tjanez** [comment]
> Meanwhile, [Fedora 45 will upgrade OpenSSL to version 4.0](https://fedoraproject.org/wiki/Changes/OpenSSL40) which makes [libetebase builds fail in Copr](https://gitlab.gnome.org/GNOME/evolution-etesync/-/work_items/22#note_2807203) with:
> 
> ```
>   thread 'main' (336) panicked at /builddir/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/openssl-sys-0.9.108/build/main.rs:492:5:
> 
> 
>   This crate is only compatible with OpenSSL (version 1.0.1 through 1.1.1, or 3), or LibreSSL 2.5
>   through 4.1.x, but a different version of OpenSSL was found. The build is now aborting
>   due to this version mismatch.
> ```
> 
> Full build logs here: https://download.copr.fedorainfracloud.org/results/daftaupe/etesync-rs/fedora-rawhide-aarch64/10699107-libetebase/builder-live.log.gz

I've filled this as a separate issue (#49) so it doesn't get lost here.
